// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: searchrequest.proto

package step19;

public final class AddressBookProtos {
  private AddressBookProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SearchResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.SearchResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * List of Result objects
     * </pre>
     *
     * <code>optional .tutorial.SearchResponse.Result result = 1;</code>
     */
    boolean hasResult();
    /**
     * <pre>
     * List of Result objects
     * </pre>
     *
     * <code>optional .tutorial.SearchResponse.Result result = 1;</code>
     */
    step19.AddressBookProtos.SearchResponse.Result getResult();
    /**
     * <pre>
     * List of Result objects
     * </pre>
     *
     * <code>optional .tutorial.SearchResponse.Result result = 1;</code>
     */
    step19.AddressBookProtos.SearchResponse.ResultOrBuilder getResultOrBuilder();

    /**
     * <code>required string status = 2;</code>
     */
    boolean hasStatus();
    /**
     * <code>required string status = 2;</code>
     */
    java.lang.String getStatus();
    /**
     * <code>required string status = 2;</code>
     */
    com.google.protobuf.ByteString
        getStatusBytes();
  }
  /**
   * Protobuf type {@code tutorial.SearchResponse}
   */
  public  static final class SearchResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.SearchResponse)
      SearchResponseOrBuilder {
    // Use SearchResponse.newBuilder() to construct.
    private SearchResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SearchResponse() {
      status_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SearchResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              step19.AddressBookProtos.SearchResponse.Result.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = result_.toBuilder();
              }
              result_ = input.readMessage(step19.AddressBookProtos.SearchResponse.Result.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(result_);
                result_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              status_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return step19.AddressBookProtos.internal_static_tutorial_SearchResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return step19.AddressBookProtos.internal_static_tutorial_SearchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              step19.AddressBookProtos.SearchResponse.class, step19.AddressBookProtos.SearchResponse.Builder.class);
    }

    public interface ResultOrBuilder extends
        // @@protoc_insertion_point(interface_extends:tutorial.SearchResponse.Result)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string url = 1;</code>
       */
      boolean hasUrl();
      /**
       * <code>required string url = 1;</code>
       */
      java.lang.String getUrl();
      /**
       * <code>required string url = 1;</code>
       */
      com.google.protobuf.ByteString
          getUrlBytes();

      /**
       * <code>optional string title = 2;</code>
       */
      boolean hasTitle();
      /**
       * <code>optional string title = 2;</code>
       */
      java.lang.String getTitle();
      /**
       * <code>optional string title = 2;</code>
       */
      com.google.protobuf.ByteString
          getTitleBytes();

      /**
       * <pre>
       * List of snippets
       * </pre>
       *
       * <code>repeated string snippets = 3;</code>
       */
      java.util.List<java.lang.String>
          getSnippetsList();
      /**
       * <pre>
       * List of snippets
       * </pre>
       *
       * <code>repeated string snippets = 3;</code>
       */
      int getSnippetsCount();
      /**
       * <pre>
       * List of snippets
       * </pre>
       *
       * <code>repeated string snippets = 3;</code>
       */
      java.lang.String getSnippets(int index);
      /**
       * <pre>
       * List of snippets
       * </pre>
       *
       * <code>repeated string snippets = 3;</code>
       */
      com.google.protobuf.ByteString
          getSnippetsBytes(int index);
    }
    /**
     * <pre>
     * Nested message type
     * </pre>
     *
     * Protobuf type {@code tutorial.SearchResponse.Result}
     */
    public  static final class Result extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:tutorial.SearchResponse.Result)
        ResultOrBuilder {
      // Use Result.newBuilder() to construct.
      private Result(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Result() {
        url_ = "";
        title_ = "";
        snippets_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Result(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                url_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                title_ = bs;
                break;
              }
              case 26: {
                com.google.protobuf.ByteString bs = input.readBytes();
                if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                  snippets_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000004;
                }
                snippets_.add(bs);
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
            snippets_ = snippets_.getUnmodifiableView();
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return step19.AddressBookProtos.internal_static_tutorial_SearchResponse_Result_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return step19.AddressBookProtos.internal_static_tutorial_SearchResponse_Result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                step19.AddressBookProtos.SearchResponse.Result.class, step19.AddressBookProtos.SearchResponse.Result.Builder.class);
      }

      private int bitField0_;
      public static final int URL_FIELD_NUMBER = 1;
      private volatile java.lang.Object url_;
      /**
       * <code>required string url = 1;</code>
       */
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string url = 1;</code>
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            url_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string url = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TITLE_FIELD_NUMBER = 2;
      private volatile java.lang.Object title_;
      /**
       * <code>optional string title = 2;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int SNIPPETS_FIELD_NUMBER = 3;
      private com.google.protobuf.LazyStringList snippets_;
      /**
       * <pre>
       * List of snippets
       * </pre>
       *
       * <code>repeated string snippets = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getSnippetsList() {
        return snippets_;
      }
      /**
       * <pre>
       * List of snippets
       * </pre>
       *
       * <code>repeated string snippets = 3;</code>
       */
      public int getSnippetsCount() {
        return snippets_.size();
      }
      /**
       * <pre>
       * List of snippets
       * </pre>
       *
       * <code>repeated string snippets = 3;</code>
       */
      public java.lang.String getSnippets(int index) {
        return snippets_.get(index);
      }
      /**
       * <pre>
       * List of snippets
       * </pre>
       *
       * <code>repeated string snippets = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSnippetsBytes(int index) {
        return snippets_.getByteString(index);
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasUrl()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, url_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
        }
        for (int i = 0; i < snippets_.size(); i++) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, snippets_.getRaw(i));
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, url_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
        }
        {
          int dataSize = 0;
          for (int i = 0; i < snippets_.size(); i++) {
            dataSize += computeStringSizeNoTag(snippets_.getRaw(i));
          }
          size += dataSize;
          size += 1 * getSnippetsList().size();
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof step19.AddressBookProtos.SearchResponse.Result)) {
          return super.equals(obj);
        }
        step19.AddressBookProtos.SearchResponse.Result other = (step19.AddressBookProtos.SearchResponse.Result) obj;

        boolean result = true;
        result = result && (hasUrl() == other.hasUrl());
        if (hasUrl()) {
          result = result && getUrl()
              .equals(other.getUrl());
        }
        result = result && (hasTitle() == other.hasTitle());
        if (hasTitle()) {
          result = result && getTitle()
              .equals(other.getTitle());
        }
        result = result && getSnippetsList()
            .equals(other.getSnippetsList());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasUrl()) {
          hash = (37 * hash) + URL_FIELD_NUMBER;
          hash = (53 * hash) + getUrl().hashCode();
        }
        if (hasTitle()) {
          hash = (37 * hash) + TITLE_FIELD_NUMBER;
          hash = (53 * hash) + getTitle().hashCode();
        }
        if (getSnippetsCount() > 0) {
          hash = (37 * hash) + SNIPPETS_FIELD_NUMBER;
          hash = (53 * hash) + getSnippetsList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static step19.AddressBookProtos.SearchResponse.Result parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static step19.AddressBookProtos.SearchResponse.Result parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static step19.AddressBookProtos.SearchResponse.Result parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static step19.AddressBookProtos.SearchResponse.Result parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static step19.AddressBookProtos.SearchResponse.Result parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static step19.AddressBookProtos.SearchResponse.Result parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static step19.AddressBookProtos.SearchResponse.Result parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static step19.AddressBookProtos.SearchResponse.Result parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static step19.AddressBookProtos.SearchResponse.Result parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static step19.AddressBookProtos.SearchResponse.Result parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(step19.AddressBookProtos.SearchResponse.Result prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       * Nested message type
       * </pre>
       *
       * Protobuf type {@code tutorial.SearchResponse.Result}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:tutorial.SearchResponse.Result)
          step19.AddressBookProtos.SearchResponse.ResultOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return step19.AddressBookProtos.internal_static_tutorial_SearchResponse_Result_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return step19.AddressBookProtos.internal_static_tutorial_SearchResponse_Result_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  step19.AddressBookProtos.SearchResponse.Result.class, step19.AddressBookProtos.SearchResponse.Result.Builder.class);
        }

        // Construct using step19.AddressBookProtos.SearchResponse.Result.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          url_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          title_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          snippets_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return step19.AddressBookProtos.internal_static_tutorial_SearchResponse_Result_descriptor;
        }

        public step19.AddressBookProtos.SearchResponse.Result getDefaultInstanceForType() {
          return step19.AddressBookProtos.SearchResponse.Result.getDefaultInstance();
        }

        public step19.AddressBookProtos.SearchResponse.Result build() {
          step19.AddressBookProtos.SearchResponse.Result result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public step19.AddressBookProtos.SearchResponse.Result buildPartial() {
          step19.AddressBookProtos.SearchResponse.Result result = new step19.AddressBookProtos.SearchResponse.Result(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.url_ = url_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.title_ = title_;
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            snippets_ = snippets_.getUnmodifiableView();
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.snippets_ = snippets_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof step19.AddressBookProtos.SearchResponse.Result) {
            return mergeFrom((step19.AddressBookProtos.SearchResponse.Result)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(step19.AddressBookProtos.SearchResponse.Result other) {
          if (other == step19.AddressBookProtos.SearchResponse.Result.getDefaultInstance()) return this;
          if (other.hasUrl()) {
            bitField0_ |= 0x00000001;
            url_ = other.url_;
            onChanged();
          }
          if (other.hasTitle()) {
            bitField0_ |= 0x00000002;
            title_ = other.title_;
            onChanged();
          }
          if (!other.snippets_.isEmpty()) {
            if (snippets_.isEmpty()) {
              snippets_ = other.snippets_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureSnippetsIsMutable();
              snippets_.addAll(other.snippets_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasUrl()) {
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          step19.AddressBookProtos.SearchResponse.Result parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (step19.AddressBookProtos.SearchResponse.Result) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object url_ = "";
        /**
         * <code>required string url = 1;</code>
         */
        public boolean hasUrl() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string url = 1;</code>
         */
        public java.lang.String getUrl() {
          java.lang.Object ref = url_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              url_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string url = 1;</code>
         */
        public com.google.protobuf.ByteString
            getUrlBytes() {
          java.lang.Object ref = url_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            url_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string url = 1;</code>
         */
        public Builder setUrl(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          url_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string url = 1;</code>
         */
        public Builder clearUrl() {
          bitField0_ = (bitField0_ & ~0x00000001);
          url_ = getDefaultInstance().getUrl();
          onChanged();
          return this;
        }
        /**
         * <code>required string url = 1;</code>
         */
        public Builder setUrlBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          url_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object title_ = "";
        /**
         * <code>optional string title = 2;</code>
         */
        public boolean hasTitle() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string title = 2;</code>
         */
        public java.lang.String getTitle() {
          java.lang.Object ref = title_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              title_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string title = 2;</code>
         */
        public com.google.protobuf.ByteString
            getTitleBytes() {
          java.lang.Object ref = title_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            title_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string title = 2;</code>
         */
        public Builder setTitle(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          title_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string title = 2;</code>
         */
        public Builder clearTitle() {
          bitField0_ = (bitField0_ & ~0x00000002);
          title_ = getDefaultInstance().getTitle();
          onChanged();
          return this;
        }
        /**
         * <code>optional string title = 2;</code>
         */
        public Builder setTitleBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          title_ = value;
          onChanged();
          return this;
        }

        private com.google.protobuf.LazyStringList snippets_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureSnippetsIsMutable() {
          if (!((bitField0_ & 0x00000004) == 0x00000004)) {
            snippets_ = new com.google.protobuf.LazyStringArrayList(snippets_);
            bitField0_ |= 0x00000004;
           }
        }
        /**
         * <pre>
         * List of snippets
         * </pre>
         *
         * <code>repeated string snippets = 3;</code>
         */
        public com.google.protobuf.ProtocolStringList
            getSnippetsList() {
          return snippets_.getUnmodifiableView();
        }
        /**
         * <pre>
         * List of snippets
         * </pre>
         *
         * <code>repeated string snippets = 3;</code>
         */
        public int getSnippetsCount() {
          return snippets_.size();
        }
        /**
         * <pre>
         * List of snippets
         * </pre>
         *
         * <code>repeated string snippets = 3;</code>
         */
        public java.lang.String getSnippets(int index) {
          return snippets_.get(index);
        }
        /**
         * <pre>
         * List of snippets
         * </pre>
         *
         * <code>repeated string snippets = 3;</code>
         */
        public com.google.protobuf.ByteString
            getSnippetsBytes(int index) {
          return snippets_.getByteString(index);
        }
        /**
         * <pre>
         * List of snippets
         * </pre>
         *
         * <code>repeated string snippets = 3;</code>
         */
        public Builder setSnippets(
            int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureSnippetsIsMutable();
          snippets_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <pre>
         * List of snippets
         * </pre>
         *
         * <code>repeated string snippets = 3;</code>
         */
        public Builder addSnippets(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureSnippetsIsMutable();
          snippets_.add(value);
          onChanged();
          return this;
        }
        /**
         * <pre>
         * List of snippets
         * </pre>
         *
         * <code>repeated string snippets = 3;</code>
         */
        public Builder addAllSnippets(
            java.lang.Iterable<java.lang.String> values) {
          ensureSnippetsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, snippets_);
          onChanged();
          return this;
        }
        /**
         * <pre>
         * List of snippets
         * </pre>
         *
         * <code>repeated string snippets = 3;</code>
         */
        public Builder clearSnippets() {
          snippets_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
          return this;
        }
        /**
         * <pre>
         * List of snippets
         * </pre>
         *
         * <code>repeated string snippets = 3;</code>
         */
        public Builder addSnippetsBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureSnippetsIsMutable();
          snippets_.add(value);
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:tutorial.SearchResponse.Result)
      }

      // @@protoc_insertion_point(class_scope:tutorial.SearchResponse.Result)
      private static final step19.AddressBookProtos.SearchResponse.Result DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new step19.AddressBookProtos.SearchResponse.Result();
      }

      public static step19.AddressBookProtos.SearchResponse.Result getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Result>
          PARSER = new com.google.protobuf.AbstractParser<Result>() {
        public Result parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Result(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Result> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Result> getParserForType() {
        return PARSER;
      }

      public step19.AddressBookProtos.SearchResponse.Result getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int RESULT_FIELD_NUMBER = 1;
    private step19.AddressBookProtos.SearchResponse.Result result_;
    /**
     * <pre>
     * List of Result objects
     * </pre>
     *
     * <code>optional .tutorial.SearchResponse.Result result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * List of Result objects
     * </pre>
     *
     * <code>optional .tutorial.SearchResponse.Result result = 1;</code>
     */
    public step19.AddressBookProtos.SearchResponse.Result getResult() {
      return result_ == null ? step19.AddressBookProtos.SearchResponse.Result.getDefaultInstance() : result_;
    }
    /**
     * <pre>
     * List of Result objects
     * </pre>
     *
     * <code>optional .tutorial.SearchResponse.Result result = 1;</code>
     */
    public step19.AddressBookProtos.SearchResponse.ResultOrBuilder getResultOrBuilder() {
      return result_ == null ? step19.AddressBookProtos.SearchResponse.Result.getDefaultInstance() : result_;
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private volatile java.lang.Object status_;
    /**
     * <code>required string status = 2;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string status = 2;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          status_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string status = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasResult()) {
        if (!getResult().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getResult());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, status_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getResult());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof step19.AddressBookProtos.SearchResponse)) {
        return super.equals(obj);
      }
      step19.AddressBookProtos.SearchResponse other = (step19.AddressBookProtos.SearchResponse) obj;

      boolean result = true;
      result = result && (hasResult() == other.hasResult());
      if (hasResult()) {
        result = result && getResult()
            .equals(other.getResult());
      }
      result = result && (hasStatus() == other.hasStatus());
      if (hasStatus()) {
        result = result && getStatus()
            .equals(other.getStatus());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasResult()) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResult().hashCode();
      }
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static step19.AddressBookProtos.SearchResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static step19.AddressBookProtos.SearchResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static step19.AddressBookProtos.SearchResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static step19.AddressBookProtos.SearchResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static step19.AddressBookProtos.SearchResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static step19.AddressBookProtos.SearchResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static step19.AddressBookProtos.SearchResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static step19.AddressBookProtos.SearchResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static step19.AddressBookProtos.SearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static step19.AddressBookProtos.SearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(step19.AddressBookProtos.SearchResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.SearchResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.SearchResponse)
        step19.AddressBookProtos.SearchResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return step19.AddressBookProtos.internal_static_tutorial_SearchResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return step19.AddressBookProtos.internal_static_tutorial_SearchResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                step19.AddressBookProtos.SearchResponse.class, step19.AddressBookProtos.SearchResponse.Builder.class);
      }

      // Construct using step19.AddressBookProtos.SearchResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResultFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (resultBuilder_ == null) {
          result_ = null;
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return step19.AddressBookProtos.internal_static_tutorial_SearchResponse_descriptor;
      }

      public step19.AddressBookProtos.SearchResponse getDefaultInstanceForType() {
        return step19.AddressBookProtos.SearchResponse.getDefaultInstance();
      }

      public step19.AddressBookProtos.SearchResponse build() {
        step19.AddressBookProtos.SearchResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public step19.AddressBookProtos.SearchResponse buildPartial() {
        step19.AddressBookProtos.SearchResponse result = new step19.AddressBookProtos.SearchResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (resultBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof step19.AddressBookProtos.SearchResponse) {
          return mergeFrom((step19.AddressBookProtos.SearchResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(step19.AddressBookProtos.SearchResponse other) {
        if (other == step19.AddressBookProtos.SearchResponse.getDefaultInstance()) return this;
        if (other.hasResult()) {
          mergeResult(other.getResult());
        }
        if (other.hasStatus()) {
          bitField0_ |= 0x00000002;
          status_ = other.status_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStatus()) {
          return false;
        }
        if (hasResult()) {
          if (!getResult().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        step19.AddressBookProtos.SearchResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (step19.AddressBookProtos.SearchResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private step19.AddressBookProtos.SearchResponse.Result result_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          step19.AddressBookProtos.SearchResponse.Result, step19.AddressBookProtos.SearchResponse.Result.Builder, step19.AddressBookProtos.SearchResponse.ResultOrBuilder> resultBuilder_;
      /**
       * <pre>
       * List of Result objects
       * </pre>
       *
       * <code>optional .tutorial.SearchResponse.Result result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * List of Result objects
       * </pre>
       *
       * <code>optional .tutorial.SearchResponse.Result result = 1;</code>
       */
      public step19.AddressBookProtos.SearchResponse.Result getResult() {
        if (resultBuilder_ == null) {
          return result_ == null ? step19.AddressBookProtos.SearchResponse.Result.getDefaultInstance() : result_;
        } else {
          return resultBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * List of Result objects
       * </pre>
       *
       * <code>optional .tutorial.SearchResponse.Result result = 1;</code>
       */
      public Builder setResult(step19.AddressBookProtos.SearchResponse.Result value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          result_ = value;
          onChanged();
        } else {
          resultBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * List of Result objects
       * </pre>
       *
       * <code>optional .tutorial.SearchResponse.Result result = 1;</code>
       */
      public Builder setResult(
          step19.AddressBookProtos.SearchResponse.Result.Builder builderForValue) {
        if (resultBuilder_ == null) {
          result_ = builderForValue.build();
          onChanged();
        } else {
          resultBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * List of Result objects
       * </pre>
       *
       * <code>optional .tutorial.SearchResponse.Result result = 1;</code>
       */
      public Builder mergeResult(step19.AddressBookProtos.SearchResponse.Result value) {
        if (resultBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              result_ != null &&
              result_ != step19.AddressBookProtos.SearchResponse.Result.getDefaultInstance()) {
            result_ =
              step19.AddressBookProtos.SearchResponse.Result.newBuilder(result_).mergeFrom(value).buildPartial();
          } else {
            result_ = value;
          }
          onChanged();
        } else {
          resultBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * List of Result objects
       * </pre>
       *
       * <code>optional .tutorial.SearchResponse.Result result = 1;</code>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = null;
          onChanged();
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <pre>
       * List of Result objects
       * </pre>
       *
       * <code>optional .tutorial.SearchResponse.Result result = 1;</code>
       */
      public step19.AddressBookProtos.SearchResponse.Result.Builder getResultBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getResultFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * List of Result objects
       * </pre>
       *
       * <code>optional .tutorial.SearchResponse.Result result = 1;</code>
       */
      public step19.AddressBookProtos.SearchResponse.ResultOrBuilder getResultOrBuilder() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilder();
        } else {
          return result_ == null ?
              step19.AddressBookProtos.SearchResponse.Result.getDefaultInstance() : result_;
        }
      }
      /**
       * <pre>
       * List of Result objects
       * </pre>
       *
       * <code>optional .tutorial.SearchResponse.Result result = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          step19.AddressBookProtos.SearchResponse.Result, step19.AddressBookProtos.SearchResponse.Result.Builder, step19.AddressBookProtos.SearchResponse.ResultOrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              step19.AddressBookProtos.SearchResponse.Result, step19.AddressBookProtos.SearchResponse.Result.Builder, step19.AddressBookProtos.SearchResponse.ResultOrBuilder>(
                  getResult(),
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }

      private java.lang.Object status_ = "";
      /**
       * <code>required string status = 2;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string status = 2;</code>
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            status_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string status = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string status = 2;</code>
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string status = 2;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <code>required string status = 2;</code>
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.SearchResponse)
    }

    // @@protoc_insertion_point(class_scope:tutorial.SearchResponse)
    private static final step19.AddressBookProtos.SearchResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new step19.AddressBookProtos.SearchResponse();
    }

    public static step19.AddressBookProtos.SearchResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SearchResponse>
        PARSER = new com.google.protobuf.AbstractParser<SearchResponse>() {
      public SearchResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SearchResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SearchResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchResponse> getParserForType() {
      return PARSER;
    }

    public step19.AddressBookProtos.SearchResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_SearchResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_SearchResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_SearchResponse_Result_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_SearchResponse_Result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023searchrequest.proto\022\010tutorial\"\211\001\n\016Sear" +
      "chResponse\022/\n\006result\030\001 \001(\0132\037.tutorial.Se" +
      "archResponse.Result\022\016\n\006status\030\002 \002(\t\0326\n\006R" +
      "esult\022\013\n\003url\030\001 \002(\t\022\r\n\005title\030\002 \001(\t\022\020\n\010sni" +
      "ppets\030\003 \003(\tB\033\n\006step19B\021AddressBookProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_SearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_SearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_SearchResponse_descriptor,
        new java.lang.String[] { "Result", "Status", });
    internal_static_tutorial_SearchResponse_Result_descriptor =
      internal_static_tutorial_SearchResponse_descriptor.getNestedTypes().get(0);
    internal_static_tutorial_SearchResponse_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_SearchResponse_Result_descriptor,
        new java.lang.String[] { "Url", "Title", "Snippets", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
