// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: searchrequest.proto

package step21;

public final class AddressBookProtos {
  private AddressBookProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SearchRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.SearchRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string query = 1;</code>
     */
    boolean hasQuery();
    /**
     * <code>required string query = 1;</code>
     */
    java.lang.String getQuery();
    /**
     * <code>required string query = 1;</code>
     */
    com.google.protobuf.ByteString
        getQueryBytes();

    /**
     * <code>optional int32 page_number = 2;</code>
     */
    boolean hasPageNumber();
    /**
     * <code>optional int32 page_number = 2;</code>
     */
    int getPageNumber();

    /**
     * <code>optional int32 result_per_page = 3;</code>
     */
    boolean hasResultPerPage();
    /**
     * <code>optional int32 result_per_page = 3;</code>
     */
    int getResultPerPage();

    /**
     * <code>optional .tutorial.SearchRequest.Corpus corpus = 4;</code>
     */
    boolean hasCorpus();
    /**
     * <code>optional .tutorial.SearchRequest.Corpus corpus = 4;</code>
     */
    step21.AddressBookProtos.SearchRequest.Corpus getCorpus();

    /**
     * <code>optional string corpusText = 5;</code>
     */
    boolean hasCorpusText();
    /**
     * <code>optional string corpusText = 5;</code>
     */
    java.lang.String getCorpusText();
    /**
     * <code>optional string corpusText = 5;</code>
     */
    com.google.protobuf.ByteString
        getCorpusTextBytes();

    /**
     * <code>optional int32 corpusId = 6;</code>
     */
    boolean hasCorpusId();
    /**
     * <code>optional int32 corpusId = 6;</code>
     */
    int getCorpusId();

    public step21.AddressBookProtos.SearchRequest.TestOneofCase getTestOneofCase();
  }
  /**
   * Protobuf type {@code tutorial.SearchRequest}
   */
  public  static final class SearchRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.SearchRequest)
      SearchRequestOrBuilder {
    // Use SearchRequest.newBuilder() to construct.
    private SearchRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SearchRequest() {
      query_ = "";
      pageNumber_ = 0;
      resultPerPage_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SearchRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              query_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              pageNumber_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              resultPerPage_ = input.readInt32();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              step21.AddressBookProtos.SearchRequest.Corpus value = step21.AddressBookProtos.SearchRequest.Corpus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                testOneofCase_ = 4;
                testOneof_ = rawValue;
              }
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              testOneofCase_ = 5;
              testOneof_ = bs;
              break;
            }
            case 48: {
              testOneofCase_ = 6;
              testOneof_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return step21.AddressBookProtos.internal_static_tutorial_SearchRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return step21.AddressBookProtos.internal_static_tutorial_SearchRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              step21.AddressBookProtos.SearchRequest.class, step21.AddressBookProtos.SearchRequest.Builder.class);
    }

    /**
     * Protobuf enum {@code tutorial.SearchRequest.Corpus}
     */
    public enum Corpus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNIVERSAL = 0;</code>
       */
      UNIVERSAL(0),
      /**
       * <code>WEB = 1;</code>
       */
      WEB(1),
      /**
       * <code>IMAGES = 2;</code>
       */
      IMAGES(2),
      /**
       * <code>LOCAL = 3;</code>
       */
      LOCAL(3),
      /**
       * <code>NEWS = 4;</code>
       */
      NEWS(4),
      /**
       * <code>PRODUCTS = 5;</code>
       */
      PRODUCTS(5),
      /**
       * <code>VIDEO = 6;</code>
       */
      VIDEO(6),
      ;

      /**
       * <code>UNIVERSAL = 0;</code>
       */
      public static final int UNIVERSAL_VALUE = 0;
      /**
       * <code>WEB = 1;</code>
       */
      public static final int WEB_VALUE = 1;
      /**
       * <code>IMAGES = 2;</code>
       */
      public static final int IMAGES_VALUE = 2;
      /**
       * <code>LOCAL = 3;</code>
       */
      public static final int LOCAL_VALUE = 3;
      /**
       * <code>NEWS = 4;</code>
       */
      public static final int NEWS_VALUE = 4;
      /**
       * <code>PRODUCTS = 5;</code>
       */
      public static final int PRODUCTS_VALUE = 5;
      /**
       * <code>VIDEO = 6;</code>
       */
      public static final int VIDEO_VALUE = 6;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Corpus valueOf(int value) {
        return forNumber(value);
      }

      public static Corpus forNumber(int value) {
        switch (value) {
          case 0: return UNIVERSAL;
          case 1: return WEB;
          case 2: return IMAGES;
          case 3: return LOCAL;
          case 4: return NEWS;
          case 5: return PRODUCTS;
          case 6: return VIDEO;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Corpus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Corpus> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Corpus>() {
              public Corpus findValueByNumber(int number) {
                return Corpus.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return step21.AddressBookProtos.SearchRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final Corpus[] VALUES = values();

      public static Corpus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Corpus(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tutorial.SearchRequest.Corpus)
    }

    private int bitField0_;
    private int testOneofCase_ = 0;
    private java.lang.Object testOneof_;
    public enum TestOneofCase
        implements com.google.protobuf.Internal.EnumLite {
      CORPUS(4),
      CORPUSTEXT(5),
      CORPUSID(6),
      TESTONEOF_NOT_SET(0);
      private final int value;
      private TestOneofCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TestOneofCase valueOf(int value) {
        return forNumber(value);
      }

      public static TestOneofCase forNumber(int value) {
        switch (value) {
          case 4: return CORPUS;
          case 5: return CORPUSTEXT;
          case 6: return CORPUSID;
          case 0: return TESTONEOF_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public TestOneofCase
    getTestOneofCase() {
      return TestOneofCase.forNumber(
          testOneofCase_);
    }

    public static final int QUERY_FIELD_NUMBER = 1;
    private volatile java.lang.Object query_;
    /**
     * <code>required string query = 1;</code>
     */
    public boolean hasQuery() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string query = 1;</code>
     */
    public java.lang.String getQuery() {
      java.lang.Object ref = query_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          query_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string query = 1;</code>
     */
    public com.google.protobuf.ByteString
        getQueryBytes() {
      java.lang.Object ref = query_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        query_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAGE_NUMBER_FIELD_NUMBER = 2;
    private int pageNumber_;
    /**
     * <code>optional int32 page_number = 2;</code>
     */
    public boolean hasPageNumber() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 page_number = 2;</code>
     */
    public int getPageNumber() {
      return pageNumber_;
    }

    public static final int RESULT_PER_PAGE_FIELD_NUMBER = 3;
    private int resultPerPage_;
    /**
     * <code>optional int32 result_per_page = 3;</code>
     */
    public boolean hasResultPerPage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 result_per_page = 3;</code>
     */
    public int getResultPerPage() {
      return resultPerPage_;
    }

    public static final int CORPUS_FIELD_NUMBER = 4;
    /**
     * <code>optional .tutorial.SearchRequest.Corpus corpus = 4;</code>
     */
    public boolean hasCorpus() {
      return testOneofCase_ == 4;
    }
    /**
     * <code>optional .tutorial.SearchRequest.Corpus corpus = 4;</code>
     */
    public step21.AddressBookProtos.SearchRequest.Corpus getCorpus() {
      if (testOneofCase_ == 4) {
        step21.AddressBookProtos.SearchRequest.Corpus result = step21.AddressBookProtos.SearchRequest.Corpus.valueOf(
            (java.lang.Integer) testOneof_);
        return result == null ? step21.AddressBookProtos.SearchRequest.Corpus.UNIVERSAL : result;
      }
      return step21.AddressBookProtos.SearchRequest.Corpus.UNIVERSAL;
    }

    public static final int CORPUSTEXT_FIELD_NUMBER = 5;
    /**
     * <code>optional string corpusText = 5;</code>
     */
    public boolean hasCorpusText() {
      return testOneofCase_ == 5;
    }
    /**
     * <code>optional string corpusText = 5;</code>
     */
    public java.lang.String getCorpusText() {
      java.lang.Object ref = "";
      if (testOneofCase_ == 5) {
        ref = testOneof_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8() && (testOneofCase_ == 5)) {
          testOneof_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string corpusText = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCorpusTextBytes() {
      java.lang.Object ref = "";
      if (testOneofCase_ == 5) {
        ref = testOneof_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (testOneofCase_ == 5) {
          testOneof_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CORPUSID_FIELD_NUMBER = 6;
    /**
     * <code>optional int32 corpusId = 6;</code>
     */
    public boolean hasCorpusId() {
      return testOneofCase_ == 6;
    }
    /**
     * <code>optional int32 corpusId = 6;</code>
     */
    public int getCorpusId() {
      if (testOneofCase_ == 6) {
        return (java.lang.Integer) testOneof_;
      }
      return 0;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasQuery()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, query_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, pageNumber_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, resultPerPage_);
      }
      if (testOneofCase_ == 4) {
        output.writeEnum(4, ((java.lang.Integer) testOneof_));
      }
      if (testOneofCase_ == 5) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, testOneof_);
      }
      if (testOneofCase_ == 6) {
        output.writeInt32(
            6, (int)((java.lang.Integer) testOneof_));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, query_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pageNumber_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, resultPerPage_);
      }
      if (testOneofCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, ((java.lang.Integer) testOneof_));
      }
      if (testOneofCase_ == 5) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, testOneof_);
      }
      if (testOneofCase_ == 6) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(
              6, (int)((java.lang.Integer) testOneof_));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof step21.AddressBookProtos.SearchRequest)) {
        return super.equals(obj);
      }
      step21.AddressBookProtos.SearchRequest other = (step21.AddressBookProtos.SearchRequest) obj;

      boolean result = true;
      result = result && (hasQuery() == other.hasQuery());
      if (hasQuery()) {
        result = result && getQuery()
            .equals(other.getQuery());
      }
      result = result && (hasPageNumber() == other.hasPageNumber());
      if (hasPageNumber()) {
        result = result && (getPageNumber()
            == other.getPageNumber());
      }
      result = result && (hasResultPerPage() == other.hasResultPerPage());
      if (hasResultPerPage()) {
        result = result && (getResultPerPage()
            == other.getResultPerPage());
      }
      result = result && getTestOneofCase().equals(
          other.getTestOneofCase());
      if (!result) return false;
      switch (testOneofCase_) {
        case 4:
          result = result && getCorpus()
              .equals(other.getCorpus());
          break;
        case 5:
          result = result && getCorpusText()
              .equals(other.getCorpusText());
          break;
        case 6:
          result = result && (getCorpusId()
              == other.getCorpusId());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasQuery()) {
        hash = (37 * hash) + QUERY_FIELD_NUMBER;
        hash = (53 * hash) + getQuery().hashCode();
      }
      if (hasPageNumber()) {
        hash = (37 * hash) + PAGE_NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getPageNumber();
      }
      if (hasResultPerPage()) {
        hash = (37 * hash) + RESULT_PER_PAGE_FIELD_NUMBER;
        hash = (53 * hash) + getResultPerPage();
      }
      switch (testOneofCase_) {
        case 4:
          hash = (37 * hash) + CORPUS_FIELD_NUMBER;
          hash = (53 * hash) + getCorpus().getNumber();
          break;
        case 5:
          hash = (37 * hash) + CORPUSTEXT_FIELD_NUMBER;
          hash = (53 * hash) + getCorpusText().hashCode();
          break;
        case 6:
          hash = (37 * hash) + CORPUSID_FIELD_NUMBER;
          hash = (53 * hash) + getCorpusId();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static step21.AddressBookProtos.SearchRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static step21.AddressBookProtos.SearchRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static step21.AddressBookProtos.SearchRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static step21.AddressBookProtos.SearchRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static step21.AddressBookProtos.SearchRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static step21.AddressBookProtos.SearchRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static step21.AddressBookProtos.SearchRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static step21.AddressBookProtos.SearchRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static step21.AddressBookProtos.SearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static step21.AddressBookProtos.SearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(step21.AddressBookProtos.SearchRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.SearchRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.SearchRequest)
        step21.AddressBookProtos.SearchRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return step21.AddressBookProtos.internal_static_tutorial_SearchRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return step21.AddressBookProtos.internal_static_tutorial_SearchRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                step21.AddressBookProtos.SearchRequest.class, step21.AddressBookProtos.SearchRequest.Builder.class);
      }

      // Construct using step21.AddressBookProtos.SearchRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        query_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        pageNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        resultPerPage_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        testOneofCase_ = 0;
        testOneof_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return step21.AddressBookProtos.internal_static_tutorial_SearchRequest_descriptor;
      }

      public step21.AddressBookProtos.SearchRequest getDefaultInstanceForType() {
        return step21.AddressBookProtos.SearchRequest.getDefaultInstance();
      }

      public step21.AddressBookProtos.SearchRequest build() {
        step21.AddressBookProtos.SearchRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public step21.AddressBookProtos.SearchRequest buildPartial() {
        step21.AddressBookProtos.SearchRequest result = new step21.AddressBookProtos.SearchRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.query_ = query_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pageNumber_ = pageNumber_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.resultPerPage_ = resultPerPage_;
        if (testOneofCase_ == 4) {
          result.testOneof_ = testOneof_;
        }
        if (testOneofCase_ == 5) {
          result.testOneof_ = testOneof_;
        }
        if (testOneofCase_ == 6) {
          result.testOneof_ = testOneof_;
        }
        result.bitField0_ = to_bitField0_;
        result.testOneofCase_ = testOneofCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof step21.AddressBookProtos.SearchRequest) {
          return mergeFrom((step21.AddressBookProtos.SearchRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(step21.AddressBookProtos.SearchRequest other) {
        if (other == step21.AddressBookProtos.SearchRequest.getDefaultInstance()) return this;
        if (other.hasQuery()) {
          bitField0_ |= 0x00000001;
          query_ = other.query_;
          onChanged();
        }
        if (other.hasPageNumber()) {
          setPageNumber(other.getPageNumber());
        }
        if (other.hasResultPerPage()) {
          setResultPerPage(other.getResultPerPage());
        }
        switch (other.getTestOneofCase()) {
          case CORPUS: {
            setCorpus(other.getCorpus());
            break;
          }
          case CORPUSTEXT: {
            testOneofCase_ = 5;
            testOneof_ = other.testOneof_;
            onChanged();
            break;
          }
          case CORPUSID: {
            setCorpusId(other.getCorpusId());
            break;
          }
          case TESTONEOF_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasQuery()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        step21.AddressBookProtos.SearchRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (step21.AddressBookProtos.SearchRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int testOneofCase_ = 0;
      private java.lang.Object testOneof_;
      public TestOneofCase
          getTestOneofCase() {
        return TestOneofCase.forNumber(
            testOneofCase_);
      }

      public Builder clearTestOneof() {
        testOneofCase_ = 0;
        testOneof_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private java.lang.Object query_ = "";
      /**
       * <code>required string query = 1;</code>
       */
      public boolean hasQuery() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string query = 1;</code>
       */
      public java.lang.String getQuery() {
        java.lang.Object ref = query_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            query_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string query = 1;</code>
       */
      public com.google.protobuf.ByteString
          getQueryBytes() {
        java.lang.Object ref = query_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          query_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string query = 1;</code>
       */
      public Builder setQuery(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        query_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string query = 1;</code>
       */
      public Builder clearQuery() {
        bitField0_ = (bitField0_ & ~0x00000001);
        query_ = getDefaultInstance().getQuery();
        onChanged();
        return this;
      }
      /**
       * <code>required string query = 1;</code>
       */
      public Builder setQueryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        query_ = value;
        onChanged();
        return this;
      }

      private int pageNumber_ ;
      /**
       * <code>optional int32 page_number = 2;</code>
       */
      public boolean hasPageNumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 page_number = 2;</code>
       */
      public int getPageNumber() {
        return pageNumber_;
      }
      /**
       * <code>optional int32 page_number = 2;</code>
       */
      public Builder setPageNumber(int value) {
        bitField0_ |= 0x00000002;
        pageNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 page_number = 2;</code>
       */
      public Builder clearPageNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pageNumber_ = 0;
        onChanged();
        return this;
      }

      private int resultPerPage_ ;
      /**
       * <code>optional int32 result_per_page = 3;</code>
       */
      public boolean hasResultPerPage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 result_per_page = 3;</code>
       */
      public int getResultPerPage() {
        return resultPerPage_;
      }
      /**
       * <code>optional int32 result_per_page = 3;</code>
       */
      public Builder setResultPerPage(int value) {
        bitField0_ |= 0x00000004;
        resultPerPage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 result_per_page = 3;</code>
       */
      public Builder clearResultPerPage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        resultPerPage_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>optional .tutorial.SearchRequest.Corpus corpus = 4;</code>
       */
      public boolean hasCorpus() {
        return testOneofCase_ == 4;
      }
      /**
       * <code>optional .tutorial.SearchRequest.Corpus corpus = 4;</code>
       */
      public step21.AddressBookProtos.SearchRequest.Corpus getCorpus() {
        if (testOneofCase_ == 4) {
          step21.AddressBookProtos.SearchRequest.Corpus result = step21.AddressBookProtos.SearchRequest.Corpus.valueOf(
              (java.lang.Integer) testOneof_);
          return result == null ? step21.AddressBookProtos.SearchRequest.Corpus.UNIVERSAL : result;
        }
        return step21.AddressBookProtos.SearchRequest.Corpus.UNIVERSAL;
      }
      /**
       * <code>optional .tutorial.SearchRequest.Corpus corpus = 4;</code>
       */
      public Builder setCorpus(step21.AddressBookProtos.SearchRequest.Corpus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        testOneofCase_ = 4;
        testOneof_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .tutorial.SearchRequest.Corpus corpus = 4;</code>
       */
      public Builder clearCorpus() {
        if (testOneofCase_ == 4) {
          testOneofCase_ = 0;
          testOneof_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional string corpusText = 5;</code>
       */
      public boolean hasCorpusText() {
        return testOneofCase_ == 5;
      }
      /**
       * <code>optional string corpusText = 5;</code>
       */
      public java.lang.String getCorpusText() {
        java.lang.Object ref = "";
        if (testOneofCase_ == 5) {
          ref = testOneof_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (testOneofCase_ == 5) {
            if (bs.isValidUtf8()) {
              testOneof_ = s;
            }
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string corpusText = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCorpusTextBytes() {
        java.lang.Object ref = "";
        if (testOneofCase_ == 5) {
          ref = testOneof_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (testOneofCase_ == 5) {
            testOneof_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string corpusText = 5;</code>
       */
      public Builder setCorpusText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  testOneofCase_ = 5;
        testOneof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string corpusText = 5;</code>
       */
      public Builder clearCorpusText() {
        if (testOneofCase_ == 5) {
          testOneofCase_ = 0;
          testOneof_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional string corpusText = 5;</code>
       */
      public Builder setCorpusTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  testOneofCase_ = 5;
        testOneof_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional int32 corpusId = 6;</code>
       */
      public boolean hasCorpusId() {
        return testOneofCase_ == 6;
      }
      /**
       * <code>optional int32 corpusId = 6;</code>
       */
      public int getCorpusId() {
        if (testOneofCase_ == 6) {
          return (java.lang.Integer) testOneof_;
        }
        return 0;
      }
      /**
       * <code>optional int32 corpusId = 6;</code>
       */
      public Builder setCorpusId(int value) {
        testOneofCase_ = 6;
        testOneof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 corpusId = 6;</code>
       */
      public Builder clearCorpusId() {
        if (testOneofCase_ == 6) {
          testOneofCase_ = 0;
          testOneof_ = null;
          onChanged();
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.SearchRequest)
    }

    // @@protoc_insertion_point(class_scope:tutorial.SearchRequest)
    private static final step21.AddressBookProtos.SearchRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new step21.AddressBookProtos.SearchRequest();
    }

    public static step21.AddressBookProtos.SearchRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SearchRequest>
        PARSER = new com.google.protobuf.AbstractParser<SearchRequest>() {
      public SearchRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SearchRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SearchRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchRequest> getParserForType() {
      return PARSER;
    }

    public step21.AddressBookProtos.SearchRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_SearchRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_SearchRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023searchrequest.proto\022\010tutorial\"\222\002\n\rSear" +
      "chRequest\022\r\n\005query\030\001 \002(\t\022\023\n\013page_number\030" +
      "\002 \001(\005\022\027\n\017result_per_page\030\003 \001(\005\0220\n\006corpus" +
      "\030\004 \001(\0162\036.tutorial.SearchRequest.CorpusH\000" +
      "\022\024\n\ncorpusText\030\005 \001(\tH\000\022\022\n\010corpusId\030\006 \001(\005" +
      "H\000\"Z\n\006Corpus\022\r\n\tUNIVERSAL\020\000\022\007\n\003WEB\020\001\022\n\n\006" +
      "IMAGES\020\002\022\t\n\005LOCAL\020\003\022\010\n\004NEWS\020\004\022\014\n\010PRODUCT" +
      "S\020\005\022\t\n\005VIDEO\020\006B\014\n\ntest_oneofB\033\n\006step21B\021" +
      "AddressBookProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_SearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_SearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_SearchRequest_descriptor,
        new java.lang.String[] { "Query", "PageNumber", "ResultPerPage", "Corpus", "CorpusText", "CorpusId", "TestOneof", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
